
    create table Canchas (
        cod_canchas bigint generated by default as identity (start with 1),
        esta_Iluminada boolean not null,
        nombre varchar(255),
        cod_color_cod_Color bigint,
        primary key (cod_canchas)
    )

    create table Colores (
        cod_Color bigint generated by default as identity (start with 1),
        descripcion varchar(255),
        primary key (cod_Color)
    )

    create table Constructores (
        cod_Constructor bigint generated by default as identity (start with 1),
        domicilio varchar(255),
        nombre varchar(255),
        primary key (cod_Constructor)
    )

    create table Jugadores (
        cod_Jugador bigint generated by default as identity (start with 1),
        apellido varchar(255),
        domicilio varchar(255),
        nacimiento integer not null,
        nombre varchar(255),
        telefono varchar(255),
        paleta_cod_Paleta bigint,
        primary key (cod_Jugador)
    )

    create table Paletas (
        cod_Paleta bigint generated by default as identity (start with 1),
        grosor float not null,
        nombre varchar(255),
        cod_Color_cod_Color bigint,
        cod_Constructor_cod_Constructor bigint,
        primary key (cod_Paleta)
    )

    create table Participacion (
        cod_Jugador bigint generated by default as identity (start with 1),
        cod_Paleta_cod_Paleta bigint,
        cod_Partido_cod_Partido bigint,
        cod_jugador_cod_Jugador bigint,
        primary key (cod_Jugador)
    )

    create table Partidos (
        cod_Partido bigint generated by default as identity (start with 1),
        fin_Partido timestamp,
        inicio_partido timestamp,
        cancha_cod_canchas bigint,
        color_cod_Color bigint,
        jugador_Responsable_cod_Jugador bigint,
        primary key (cod_Partido)
    )

    alter table Canchas 
        add constraint FK_b7y7045vdpwkg7mu5of6ku4xi 
        foreign key (cod_color_cod_Color) 
        references Colores

    alter table Jugadores 
        add constraint FK_6pfase94xr0jyqbe2q2nm7ykh 
        foreign key (paleta_cod_Paleta) 
        references Paletas

    alter table Paletas 
        add constraint FK_1ppp0i4ep63esuwrb15u11ygt 
        foreign key (cod_Color_cod_Color) 
        references Colores

    alter table Paletas 
        add constraint FK_6qwvll3kfo7vosls4pifbevvn 
        foreign key (cod_Constructor_cod_Constructor) 
        references Constructores

    alter table Participacion 
        add constraint FK_6kpnlffww9yc6f8agpew10l6d 
        foreign key (cod_Paleta_cod_Paleta) 
        references Paletas

    alter table Participacion 
        add constraint FK_bl0fvj6dbxrptweyk4i8cwv9j 
        foreign key (cod_Partido_cod_Partido) 
        references Partidos

    alter table Participacion 
        add constraint FK_88yvuqrji2mynbtx9bqlki4v3 
        foreign key (cod_jugador_cod_Jugador) 
        references Jugadores

    alter table Partidos 
        add constraint FK_rxnbcfci6r65sl3gu695bxyen 
        foreign key (cancha_cod_canchas) 
        references Canchas

    alter table Partidos 
        add constraint FK_kb2ncbxv7od8hpmdvwhkxgung 
        foreign key (color_cod_Color) 
        references Colores

    alter table Partidos 
        add constraint FK_29wt3emg5rds6otfroympdbw9 
        foreign key (jugador_Responsable_cod_Jugador) 
        references Jugadores
