
    create table Colores (
        cod_Color bigint generated by default as identity (start with 1),
        descripcion varchar(255),
        primary key (cod_Color)
    )

    create table Constructores (
        cod_Constructor bigint generated by default as identity (start with 1),
        domicilio varchar(255),
        nombre varchar(255),
        primary key (cod_Constructor)
    )

    create table Paletas (
        cod_Paleta bigint generated by default as identity (start with 1),
        grosor float not null,
        nombre varchar(255),
        cod_Color_cod_Color bigint,
        cod_Constructor_cod_Constructor bigint,
        primary key (cod_Paleta)
    )

    alter table Paletas 
        add constraint FK_1ppp0i4ep63esuwrb15u11ygt 
        foreign key (cod_Color_cod_Color) 
        references Colores

    alter table Paletas 
        add constraint FK_6qwvll3kfo7vosls4pifbevvn 
        foreign key (cod_Constructor_cod_Constructor) 
        references Constructores
